// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package main

import (
	"flag"
	"fmt"

	"book_store/rpc/check/internal/config"
	"book_store/rpc/check/internal/server"
	"book_store/rpc/check/internal/svc"
	check "book_store/rpc/check/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/check.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	checkerSrv := server.NewCheckerServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		check.RegisterCheckerServer(grpcServer, checkerSrv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
